runtime: php55
api_version: 1

application: hnpickup
version: 13

handlers:
- url: /start_etl
  script: 1.etl/get_hnpages.php
  login: admin
- url: /robots\.txt
  static_files: 4.static/robots.txt
  upload: 4.static/robots.txt
- url: /favicon\.ico
  static_files: 4.static/favicon.ico
  upload: 4.static/favicon.ico
- url: /.*
  script: 4.static/index.html
