runtime: php55
api_version: 1
threadsafe: true

application: hnpickup
version: 13

handlers:
- url: /start_etl
  script: 1.etl/get_hnpages.php
  login: admin
- url: /robots\.txt
  static_files: 4.stat/robots.txt
  upload: 4.stat/robots.txt
- url: /favicon\.ico
  static_files: 4.stat/favicon.ico
  upload: 4.stat/favicon.ico
- url: /.*
  script: 3.rep/app.php
