runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /start_etl
  script: 1.etl/get_hnpages.php
  login: admin
- url: /robots\.txt
  static_files: 4.stat/robots.txt
  upload: 4.stat/robots.txt
- url: /favicon\.ico
  static_files: 4.stat/favicon.ico
  upload: 4.stat/favicon.ico
- url: /libs
  static_dir: 4.stat/libs
- url: /bower_components
  static_dir: bower_components
- url: /tests
  static_dir: 5.tests/html
- url: /.*
  script: 3.rep/app.php
